### ISSUE TITLE
Can  provide  some sample data for Gait?

### ISSUE THREAD

**Issue by fanbinnet** [Sage-Bionetworks/mhealthx#4]
I need do some gait research ,but can not run "walk_direction_preheel",because of  I don't have any sample data.
If can provide some sample data ?

**Comment by larssono** [comment]
There is a small set of sample data at: https://www.synapse.org/#!Synapse:syn4993293/wiki/247859 
under the table tab.  There is also a larger dataset that you can request by following the instructions at: https://www.synapse.org/#!Synapse:syn4993293/wiki/247860
